// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkUnCh_hpry7UuRRlXOJo0XCm43cpGGoc',
    appId: '1:1011534609104:web:464dc789242ddd0a1a3cd5',
    messagingSenderId: '1011534609104',
    projectId: 'edentify-thesis',
    authDomain: 'edentify-thesis.firebaseapp.com',
    storageBucket: 'edentify-thesis.firebasestorage.app',
    measurementId: 'G-NXGCK4W5ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ceWmS2WOD3ptBnUO8OaoKU7elCc4Ur4',
    appId: '1:1011534609104:android:54a3aaf4d2de6bf21a3cd5',
    messagingSenderId: '1011534609104',
    projectId: 'edentify-thesis',
    storageBucket: 'edentify-thesis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyXmwYXKIWYodrOkK4c-oeer2_hG3T3MI',
    appId: '1:1011534609104:ios:7534751c616b638f1a3cd5',
    messagingSenderId: '1011534609104',
    projectId: 'edentify-thesis',
    storageBucket: 'edentify-thesis.firebasestorage.app',
    iosBundleId: 'com.example.edentifyweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyXmwYXKIWYodrOkK4c-oeer2_hG3T3MI',
    appId: '1:1011534609104:ios:7534751c616b638f1a3cd5',
    messagingSenderId: '1011534609104',
    projectId: 'edentify-thesis',
    storageBucket: 'edentify-thesis.firebasestorage.app',
    iosBundleId: 'com.example.edentifyweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkUnCh_hpry7UuRRlXOJo0XCm43cpGGoc',
    appId: '1:1011534609104:web:f55d152aa23eced81a3cd5',
    messagingSenderId: '1011534609104',
    projectId: 'edentify-thesis',
    authDomain: 'edentify-thesis.firebaseapp.com',
    storageBucket: 'edentify-thesis.firebasestorage.app',
    measurementId: 'G-XGQF9M086Z',
  );
}
